repos:
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        args: [
          '--skip', 'ucm/csrc/**,./ucm.egg-info/**,.github/**',
          '-L', 'CANN,cann,NNAL,nnal,ASCEND,ascend,EnQue,CopyIn'
        ]
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/PyCQA/isort
    rev: 6.0.1
    hooks:
      - id: isort
        args:
            - "--profile=black"
  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.7
    hooks:
      - id: actionlint
default_stages:
  - pre-commit
  - manual