name: 🤗 Support request for new model supported from huggingface/modelscope/modelers on ucm
description: Submit a proposal/request for a new model from huggingface/modelscope/modelers on ucm
title: "[New Model]: "
labels: ["new model"]

body:
- type: markdown
  attributes:
    value: >
      #### Before submitting an issue, please make sure the issue hasn't been already addressed by searching through [the existing and past issues](https://github.com/ModelEngine-Group/unified-cache-management/issues?q=is%3Aissue%20sort%3Acreated-desc).

      #### We also highly recommend you read our official website first to know which model already supported.
- type: textarea
  attributes:
    label: The model to consider.
    description: >
      A huggingface/modelscope/modelers url, pointing to the model, e.g. https://huggingface.co/openai-community/gpt2 .
  validations:
    required: true
- type: textarea
  attributes:
    label: The closest model ucm already supports.
    description: >
      Here is the list of models already supported by unifiedcache in our official website . Which model is the most similar to the model you want to add support for?
- type: textarea
  attributes:
    label: What's your difficulty of supporting the model you want?
    description: >
      For example, any new operators or new architecture?
- type: markdown
  attributes:
    value: >
      Thanks for contributing 🎉!
