{{- $modelSpec := default (dict) .Values.servingEngineSpec.modelSpec -}}
{{- include "chart.validateDataParallelMode" (list $modelSpec) -}}
{{- include "chart.validateKvTransfer" (list $modelSpec $) -}}
