# Set to other image if needed
ARG IMAGE_SOURCE="vllm"
ARG IMAGE_NAME_VERSION="vllm-openai:nightly"

FROM ${IMAGE_SOURCE}/${IMAGE_NAME_VERSION}

ARG PIP_INDEX_URL="https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple"
ARG INSTALL_MODE="source"
ARG APT_MIRROR=""

WORKDIR /workspace

# Install unified-cache-management
COPY . /workspace/unified-cache-management

RUN pip config set global.index-url ${PIP_INDEX_URL}

# Build or link package
RUN if [ "${INSTALL_MODE}" != "package" ]; then \
        if [ -d /etc/apt/sources.list.d ] ; then \
            rm -f /etc/apt/sources.list.d/* \
        fi && \
        if [ -n "${APT_MIRROR}" ]; then \
            sed -i "s|http://.*archive.ubuntu.com|http://${APT_MIRROR}|g" /etc/apt/sources.list && \
            sed -i "s|http://.*security.ubuntu.com|http://${APT_MIRROR}|g" /etc/apt/sources.list && \
            sed -i "s|http://.*ports.ubuntu.com|http://${APT_MIRROR}|g" /etc/apt/sources.list; \
        fi && \
        apt-get update && \
        apt-get install -y --no-install-recommends git && \
        rm -rf /var/lib/apt/lists/* && \
        pip install --no-cache-dir build cmake && \
        export WORKSPACE=/workspace SKIP_TAR=1 ENABLE_SPARSE=false && \
        bash /workspace/unified-cache-management/scripts/build_cuda.sh; \
    else \
        ln -s /workspace/unified-cache-management /workspace/package; \
    fi

# Install UCM
RUN pip install /workspace/package/uc_manager-*.whl

ENTRYPOINT ["/bin/bash"]
