#****************************************
#       Multi-node Configuration        *
#****************************************
master_ip=192.168.0.205
worker_ip=192.168.0.127
export HCCL_OP_EXPANSION_MODE="AIV"
export OMP_PROC_BIND=false
export OMP_NUM_THREADS=100
export HCCL_BUFFSIZE=200
export PYTORCH_NPU_ALLOC_CONF=expandable_segments:True
export VLLM_ASCEND_ENABLE_MLAPO=1
export HCCL_INTRA_PCIE_ENABLE=1
export HCCL_INTRA_ROCE_ENABLE=0

#****************************************
#          vLLM Configuration           *
#****************************************
export ASCEND_RT_VISIBLE_DEVICES=0,1,2,3,4,5,6,7
export VLLM_LOGGING_LEVEL=INFO
model=/home/models/QwQ-32B
# If not specified, the model name will be the same as the --model argument.
# served_model_name=qwen
server_host=0.0.0.0
server_port=7850
tp_size=4
dp_size=4
dp_size_local=2
dp_rpc_port=13389
pp_size=1
seed=1024
enable_expert_parallel=false
enable_prefix_caching=false
max_model_len=20000
max_num_batch_tokens=20000
max_num_seqs=64
block_size=128
gpu_memory_utilization=0.87
# NONE | PIECEWISE | FULL | FULL_DECODE_ONLY | FULL_AND_PIECEWISE
graph_mode=FULL_DECODE_ONLY
quantization=ascend
async_scheduling=false

#****************************************
#  extra vLLM Configuration for Ascend  *
#****************************************
# method=deepseek_mtp
enable_ascend_scheduler=false
enable_torchair_graph=false

#****************************************
#          UCM  Configuration           *
#****************************************
# set true to enable UCM
ucm_enable=false
ucm_config_yaml_path=/vllm-workspace/unified-cache-management/examples/ucm_config_example.yaml


