#*****************************
#     ray   Configuration    *
#*****************************
CUDA_VISIBLE_DEVICES=1,2,3,4,5,6,7
ASCEND_RT_VISIBLE_DEVICES=1,2,3,4,5,6,7
# For multi-node and multi-gpu inference
RAY_EXPERIMENTAL_NOSET_CUDA_VISIBLE_DEVICES=1 
MASTER_IP=192.168.0.205
WORKER_IP=192.168.0.127
# Total number of nodes in multi-node inference
NODE_NUM=2


#*****************************
#     vLLM  Configuration    *
#*****************************
# Avoid the error "RuntimeError: CUDASymmetricMemoryAllocator" during multi-node, multi-GPU inference. See it in the issue: https://github.com/vllm-project/vllm/issues/24694
VLLM_ALLREDUCE_USE_SYMM_MEM=0
VLLM_LOGGING_LEVEL=INFO
MODEL=/home/models/QwQ-32B
# If not specified, the model name will be the same as the --model argument.
# SERVED_MODEL_NAME=qwen
TP_SIZE=8
DP_SIZE=1
PP_SIZE=1
# 0 | 1 ; Set 1 to enable expert parallel
ENABLE_EXPERT_PARALLEL=0
MAX_MODEL_LEN=20000
MAX_NUM_BATCH_TOKENS=20000
MAX_NUM_SEQS=64
BLOCK_SIZE=128
GPU_MEMORY_UTILIZATION=0.87
SERVER_HOST=0.0.0.0
SERVER_PORT=7850
ENABLE_PREFIX_CACHING=0
ASYNC_SCHEDULING=0
# NONE | PIECEWISE | FULL | FULL_DECODE_ONLY | FULL_AND_PIECEWISE
GRAPH_MODE=FULL_DECODE_ONLY
QUANTIZATION=None
# mp | ray ; Set mp to start single-node inference
DISTRIBUTED_EXECUTOR_BACKEND=mp


#*****************************
#     UCM  Configuration     *
#*****************************
UCM_ENABLE=1
UCM_CONFIG_YAML_PATH=/vllm-workspace/unified-cache-management/examples/ucm_config_example.yaml