#pragma once

// Generated by generate_kv_metrics.py from kv_metrics.yaml.

#include <vector>
#include "kv_metrics/standalone_metrics_backend.h"

namespace kv::metrics {

inline std::vector<MetricDescriptor> DefaultKvMetricDescriptors()
{
    return {

    };
}

}  // namespace kv::metrics
