#****************************************
#          vLLM Configuration           *
#****************************************
export CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7
export ASCEND_RT_VISIBLE_DEVICES=0,1,2,3,4,5,6,7
# Run deepseek v3.1+ on CUDA
export VLLM_USE_DEEP_GEMM=0
export VLLM_LOGGING_LEVEL=INFO
model=/home/models/QwQ-32B
# If not specified, the model name will be the same as the --model argument.
# served_model_name=qwen
server_host=0.0.0.0
server_port=7850
tp_size=8
dp_size=1
pp_size=1
enable_expert_parallel=false
enable_prefix_caching=false
max_model_len=20000
max_num_batch_tokens=20000
max_num_seqs=64
block_size=128
gpu_memory_utilization=0.87
async_scheduling=false
# NONE | PIECEWISE | FULL | FULL_DECODE_ONLY | FULL_AND_PIECEWISE
graph_mode=FULL_DECODE_ONLY
quantization=NONE
# mp | ray ; Set mp to start single-node inference
distributed_executor_backend=mp

#****************************************
#  extra vLLM Configuration for Ascend  *
#****************************************


#****************************************
#          UCM  Configuration           *
#****************************************
# set true to enable UCM
ucm_enable=true
ucm_config_yaml_path=/vllm-workspace/unified-cache-management/examples/ucm_config_example.yaml
